### PR TITLE
Added support for multiple dependencies and using response data in dependent request

### PR DESCRIPTION
**Pull request by ggutenberg**
Addresses #4 and #11.

Uses es6 template string syntax for dependent requests - https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals

Ex:
```
{
    getEmail: {
        url: 'http://localhost:3000/users/1/email'
    },
    getName: {
        url: 'http://localhost:3000/users/1/name'
    },
    deepReflection: {
        dependency: ['getEmail', 'getName'],
        method: 'POST',
        body: { email: '${dependency[0].body}', name: '${dependency[1].body}' },
        json: true,
        url: 'http://localhost:3000/users/1/deep'
    }
}
```

Notes:

If using the response from a dependency, the dependency property *must* be an array, and the es6 template reference *must* reference the dependency index you wish to use.

The code will now attempt to `JSON.parse()` a JSON body if the response header is `Content-Type: application/json`.

I have a fast computer, and the arbitrary time additions in the tests were causing them to fail (ex. server delays 250, but the test was looking for > 999 delta, but it was only ~300 delta for me), so instead of checking `> time + 999` i changed them to `> time`.

### CODE REVIEW

**Comment by victorquinn** [comment]
Wow, this is an awesome chunk of changes @ggutenberg ! Much appreciated :+1:

**Comment by victorquinn** [comment]
FYI this is published to NPM as 0.1.3

**Comment by ggutenberg** [comment]
Great!  Thanks @victorquinn .  You should update the docs on http://batch-request.socialradar.com/ as well, as they're quite good right now, and I'd hate to see this functionality not get documented.

**Comment by victorquinn** [comment]
:+1: will do!

**Comment by fawcett888** [comment]
I just discovered this library and was pleasantly surprised to see this feature when browsing the issues, though it has not yet been documented. You are also using the dependency array when the documentation states that it's not yet implemented.

**Pull request merged**
